modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="steelandsakura"
version="1.3.0"
displayName="Steel & Sakura"
displayURL="https://astralrealm.web.app"
logoFile="logo.png"
credits="Many textures from Novaskin, code by me annd with some Mcreator for basics."
authors="AstralVixen"
description="Step into a world where cherry blossoms bloom amidst dark secrets, and spirits linger in the shadows. Master the art of Katana forging, challenge fearsome onis, and uncover the secrets of the Yūgen Clan. Whether you're a samurai at heart or simply love the beauty of cherry blossoms, this mod has something for you."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.steelandsakura]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.steelandsakura]]
    modId="geckolib"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.steelandsakura]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

